### ISSUE TITLE
DevTool error

### ISSUE THREAD

**Issue by Boneshockx** [muhmiauwauWOW/AuctionHouseFilterDefaults#1]
https://github.com/muhmiauwauWOW/AuctionHouseFilterDefaults/blob/052d1c70ef8b1349d27a899c97782a1a6a719fd1/AuctionHouseFilterDefaults.lua#L24

This will throw an error when DevTool is not loaded.

**Comment by muhmiauwau** [comment]
Thank you for the heads up, i am really sorry for that. It is fixed with version 1.0.3
